{
    "name": """Real Multi Website""",
    "summary": """Yes, you can set up multi-company, multi-website, multi-theme, multi-eCommerce on a single database!""",
    "category": "eCommerce",
    "images": ["images/website_multi_company_main.png"],
    "version": "13.0.3.0.1",
    "application": True,
    "depends": [
        "mail_multi_website",
        "website",
        "ir_config_parameter_multi_company",
        "ir_rule_website",
    ],
    "external_dependencies": {"python": [], "bin": []},
    "data": [
        "views/website_views.xml",
        "views/website_menu_views.xml",
        "views/res_config_views.xml",
        "views/website_navbar_templates.xml",
        "views/res_users_view.xml",
        "data/first_action.xml",
        "security/res_security.xml",
    ],
    "qweb": [],
    "demo": ["data/demo.xml"],
    "post_load": "post_load",
    "pre_init_hook": None,
    "post_init_hook": None,
    "auto_install": False,
    "installable": True,
}
